
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: memetaverse.renderer.kernel_services
// file: memetaverse/renderer/kernel_services/emotes_kernel.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;

namespace Memetaverse.Renderer.KernelServices {
public interface IClientEmotesKernelService
{
  UniTask<TriggerExpressionResponse> TriggerExpression(TriggerExpressionRequest request);
}

public class ClientEmotesKernelService : IClientEmotesKernelService
{
  private readonly RpcClientModule module;

  public ClientEmotesKernelService(RpcClientModule module)
  {
      this.module = module;
  }

  
  public UniTask<TriggerExpressionResponse> TriggerExpression(TriggerExpressionRequest request)
  {
      return module.CallUnaryProcedure<TriggerExpressionResponse>("TriggerExpression", request);
  }

}
}
