// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: memetaverse/sdk/components/common/camera_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from memetaverse/sdk/components/common/camera_type.proto</summary>
  public static partial class CameraTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for memetaverse/sdk/components/common/camera_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CameraTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNtZW1ldGF2ZXJzZS9zZGsvY29tcG9uZW50cy9jb21tb24vY2FtZXJhX3R5",
            "cGUucHJvdG8SIW1lbWV0YXZlcnNlLnNkay5jb21wb25lbnRzLmNvbW1vbipI",
            "CgpDYW1lcmFUeXBlEhMKD0NUX0ZJUlNUX1BFUlNPThAAEhMKD0NUX1RISVJE",
            "X1BFUlNPThABEhAKDENUX0NJTkVNQVRJQxACQhSqAhFEQ0wuRUNTQ29tcG9u",
            "ZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.CameraType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CameraType {
    [pbr::OriginalName("CT_FIRST_PERSON")] CtFirstPerson = 0,
    [pbr::OriginalName("CT_THIRD_PERSON")] CtThirdPerson = 1,
    /// <summary>
    /// controlled by the scene
    /// </summary>
    [pbr::OriginalName("CT_CINEMATIC")] CtCinematic = 2,
  }

  #endregion

}

#endregion Designer generated code
