// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: memetaverse/sdk/components/common/input_action.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from memetaverse/sdk/components/common/input_action.proto</summary>
  public static partial class InputActionReflection {

    #region Descriptor
    /// <summary>File descriptor for memetaverse/sdk/components/common/input_action.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InputActionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRtZW1ldGF2ZXJzZS9zZGsvY29tcG9uZW50cy9jb21tb24vaW5wdXRfYWN0",
            "aW9uLnByb3RvEiFtZW1ldGF2ZXJzZS5zZGsuY29tcG9uZW50cy5jb21tb24q",
            "5QEKC0lucHV0QWN0aW9uEg4KCklBX1BPSU5URVIQABIOCgpJQV9QUklNQVJZ",
            "EAESEAoMSUFfU0VDT05EQVJZEAISCgoGSUFfQU5ZEAMSDgoKSUFfRk9SV0FS",
            "RBAEEg8KC0lBX0JBQ0tXQVJEEAUSDAoISUFfUklHSFQQBhILCgdJQV9MRUZU",
            "EAcSCwoHSUFfSlVNUBAIEgsKB0lBX1dBTEsQCRIPCgtJQV9BQ1RJT05fMxAK",
            "Eg8KC0lBX0FDVElPTl80EAsSDwoLSUFfQUNUSU9OXzUQDBIPCgtJQV9BQ1RJ",
            "T05fNhANKlYKEFBvaW50ZXJFdmVudFR5cGUSCgoGUEVUX1VQEAASDAoIUEVU",
            "X0RPV04QARITCg9QRVRfSE9WRVJfRU5URVIQAhITCg9QRVRfSE9WRVJfTEVB",
            "VkUQA0IUqgIRRENMLkVDU0NvbXBvbmVudHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.InputAction), typeof(global::DCL.ECSComponents.PointerEventType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum InputAction {
    [pbr::OriginalName("IA_POINTER")] IaPointer = 0,
    [pbr::OriginalName("IA_PRIMARY")] IaPrimary = 1,
    [pbr::OriginalName("IA_SECONDARY")] IaSecondary = 2,
    [pbr::OriginalName("IA_ANY")] IaAny = 3,
    [pbr::OriginalName("IA_FORWARD")] IaForward = 4,
    [pbr::OriginalName("IA_BACKWARD")] IaBackward = 5,
    [pbr::OriginalName("IA_RIGHT")] IaRight = 6,
    [pbr::OriginalName("IA_LEFT")] IaLeft = 7,
    [pbr::OriginalName("IA_JUMP")] IaJump = 8,
    [pbr::OriginalName("IA_WALK")] IaWalk = 9,
    [pbr::OriginalName("IA_ACTION_3")] IaAction3 = 10,
    [pbr::OriginalName("IA_ACTION_4")] IaAction4 = 11,
    [pbr::OriginalName("IA_ACTION_5")] IaAction5 = 12,
    [pbr::OriginalName("IA_ACTION_6")] IaAction6 = 13,
  }

  /// <summary>
  /// PointerEventType is a kind of interaction that can be detected.
  /// </summary>
  public enum PointerEventType {
    [pbr::OriginalName("PET_UP")] PetUp = 0,
    [pbr::OriginalName("PET_DOWN")] PetDown = 1,
    [pbr::OriginalName("PET_HOVER_ENTER")] PetHoverEnter = 2,
    [pbr::OriginalName("PET_HOVER_LEAVE")] PetHoverLeave = 3,
  }

  #endregion

}

#endregion Designer generated code
