// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: memetaverse/sdk/components/common/loading_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from memetaverse/sdk/components/common/loading_state.proto</summary>
  public static partial class LoadingStateReflection {

    #region Descriptor
    /// <summary>File descriptor for memetaverse/sdk/components/common/loading_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoadingStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVtZW1ldGF2ZXJzZS9zZGsvY29tcG9uZW50cy9jb21tb24vbG9hZGluZ19z",
            "dGF0ZS5wcm90bxIhbWVtZXRhdmVyc2Uuc2RrLmNvbXBvbmVudHMuY29tbW9u",
            "Kl4KDExvYWRpbmdTdGF0ZRILCgdVTktOT1dOEAASCwoHTE9BRElORxABEg0K",
            "CU5PVF9GT1VORBACEhcKE0ZJTklTSEVEX1dJVEhfRVJST1IQAxIMCghGSU5J",
            "U0hFRBAEQhSqAhFEQ0wuRUNTQ29tcG9uZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.LoadingState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum LoadingState {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("LOADING")] Loading = 1,
    [pbr::OriginalName("NOT_FOUND")] NotFound = 2,
    [pbr::OriginalName("FINISHED_WITH_ERROR")] FinishedWithError = 3,
    [pbr::OriginalName("FINISHED")] Finished = 4,
  }

  #endregion

}

#endregion Designer generated code
