// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: memetaverse/sdk/components/common/media_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from memetaverse/sdk/components/common/media_state.proto</summary>
  public static partial class MediaStateReflection {

    #region Descriptor
    /// <summary>File descriptor for memetaverse/sdk/components/common/media_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MediaStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNtZW1ldGF2ZXJzZS9zZGsvY29tcG9uZW50cy9jb21tb24vbWVkaWFfc3Rh",
            "dGUucHJvdG8SIW1lbWV0YXZlcnNlLnNkay5jb21wb25lbnRzLmNvbW1vbiqG",
            "AQoKTWVkaWFTdGF0ZRILCgdNU19OT05FEAASDAoITVNfRVJST1IQARIOCgpN",
            "U19MT0FESU5HEAISDAoITVNfUkVBRFkQAxIOCgpNU19QTEFZSU5HEAQSEAoM",
            "TVNfQlVGRkVSSU5HEAUSDgoKTVNfU0VFS0lORxAGEg0KCU1TX1BBVVNFRBAH",
            "QhSqAhFEQ0wuRUNTQ29tcG9uZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.MediaState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MediaState {
    [pbr::OriginalName("MS_NONE")] MsNone = 0,
    [pbr::OriginalName("MS_ERROR")] MsError = 1,
    [pbr::OriginalName("MS_LOADING")] MsLoading = 2,
    [pbr::OriginalName("MS_READY")] MsReady = 3,
    [pbr::OriginalName("MS_PLAYING")] MsPlaying = 4,
    [pbr::OriginalName("MS_BUFFERING")] MsBuffering = 5,
    [pbr::OriginalName("MS_SEEKING")] MsSeeking = 6,
    [pbr::OriginalName("MS_PAUSED")] MsPaused = 7,
  }

  #endregion

}

#endregion Designer generated code
