// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: memetaverse/sdk/components/common/texts.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from memetaverse/sdk/components/common/texts.proto</summary>
  public static partial class TextsReflection {

    #region Descriptor
    /// <summary>File descriptor for memetaverse/sdk/components/common/texts.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TextsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1tZW1ldGF2ZXJzZS9zZGsvY29tcG9uZW50cy9jb21tb24vdGV4dHMucHJv",
            "dG8SIW1lbWV0YXZlcnNlLnNkay5jb21wb25lbnRzLmNvbW1vbirMAQoNVGV4",
            "dEFsaWduTW9kZRIQCgxUQU1fVE9QX0xFRlQQABISCg5UQU1fVE9QX0NFTlRF",
            "UhABEhEKDVRBTV9UT1BfUklHSFQQAhITCg9UQU1fTUlERExFX0xFRlQQAxIV",
            "ChFUQU1fTUlERExFX0NFTlRFUhAEEhQKEFRBTV9NSURETEVfUklHSFQQBRIT",
            "Cg9UQU1fQk9UVE9NX0xFRlQQBhIVChFUQU1fQk9UVE9NX0NFTlRFUhAHEhQK",
            "EFRBTV9CT1RUT01fUklHSFQQCCo2CgRGb250EhAKDEZfU0FOU19TRVJJRhAA",
            "EgsKB0ZfU0VSSUYQARIPCgtGX01PTk9TUEFDRRACQhSqAhFEQ0wuRUNTQ29t",
            "cG9uZW50c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.TextAlignMode), typeof(global::DCL.ECSComponents.Font), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TextAlignMode {
    [pbr::OriginalName("TAM_TOP_LEFT")] TamTopLeft = 0,
    [pbr::OriginalName("TAM_TOP_CENTER")] TamTopCenter = 1,
    [pbr::OriginalName("TAM_TOP_RIGHT")] TamTopRight = 2,
    [pbr::OriginalName("TAM_MIDDLE_LEFT")] TamMiddleLeft = 3,
    [pbr::OriginalName("TAM_MIDDLE_CENTER")] TamMiddleCenter = 4,
    [pbr::OriginalName("TAM_MIDDLE_RIGHT")] TamMiddleRight = 5,
    [pbr::OriginalName("TAM_BOTTOM_LEFT")] TamBottomLeft = 6,
    [pbr::OriginalName("TAM_BOTTOM_CENTER")] TamBottomCenter = 7,
    [pbr::OriginalName("TAM_BOTTOM_RIGHT")] TamBottomRight = 8,
  }

  public enum Font {
    [pbr::OriginalName("F_SANS_SERIF")] FSansSerif = 0,
    [pbr::OriginalName("F_SERIF")] FSerif = 1,
    [pbr::OriginalName("F_MONOSPACE")] FMonospace = 2,
  }

  #endregion

}

#endregion Designer generated code
