// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: memetaverse/sdk/components/ui_background.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DCL.ECSComponents {

  /// <summary>Holder for reflection information generated from memetaverse/sdk/components/ui_background.proto</summary>
  public static partial class UiBackgroundReflection {

    #region Descriptor
    /// <summary>File descriptor for memetaverse/sdk/components/ui_background.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UiBackgroundReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5tZW1ldGF2ZXJzZS9zZGsvY29tcG9uZW50cy91aV9iYWNrZ3JvdW5kLnBy",
            "b3RvEhptZW1ldGF2ZXJzZS5zZGsuY29tcG9uZW50cxofbWVtZXRhdmVyc2Uv",
            "Y29tbW9uL2NvbG9ycy5wcm90bxogbWVtZXRhdmVyc2UvY29tbW9uL3RleHR1",
            "cmUucHJvdG8aJG1lbWV0YXZlcnNlL2NvbW1vbi9ib3JkZXJfcmVjdC5wcm90",
            "byK0AgoOUEJVaUJhY2tncm91bmQSLgoFY29sb3IYASABKAsyGi5tZW1ldGF2",
            "ZXJzZS5jb21tb24uQ29sb3I0SACIAQESNgoHdGV4dHVyZRgCIAEoCzIgLm1l",
            "bWV0YXZlcnNlLmNvbW1vbi5UZXh0dXJlVW5pb25IAYgBARJHCgx0ZXh0dXJl",
            "X21vZGUYAyABKA4yMS5tZW1ldGF2ZXJzZS5zZGsuY29tcG9uZW50cy5CYWNr",
            "Z3JvdW5kVGV4dHVyZU1vZGUSOwoOdGV4dHVyZV9zbGljZXMYBCABKAsyHi5t",
            "ZW1ldGF2ZXJzZS5jb21tb24uQm9yZGVyUmVjdEgCiAEBEgsKA3V2cxgFIAMo",
            "AkIICgZfY29sb3JCCgoIX3RleHR1cmVCEQoPX3RleHR1cmVfc2xpY2VzKkEK",
            "FUJhY2tncm91bmRUZXh0dXJlTW9kZRIPCgtOSU5FX1NMSUNFUxAAEgoKBkNF",
            "TlRFUhABEgsKB1NUUkVUQ0gQAkIUqgIRRENMLkVDU0NvbXBvbmVudHNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Memetaverse.Common.ColorsReflection.Descriptor, global::Memetaverse.Common.TextureReflection.Descriptor, global::Memetaverse.Common.BorderRectReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DCL.ECSComponents.BackgroundTextureMode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DCL.ECSComponents.PBUiBackground), global::DCL.ECSComponents.PBUiBackground.Parser, new[]{ "Color", "Texture", "TextureMode", "TextureSlices", "Uvs" }, new[]{ "Color", "Texture", "TextureSlices" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum BackgroundTextureMode {
    /// <summary>
    /// https://docs.unity3d.com/Manual/UIE-USS-SupportedProperties.html (Slicing section)
    /// https://forum.unity.com/threads/how-does-slicing-in-ui-tookkit-works.1235863/
    /// https://docs.unity3d.com/Manual/9SliceSprites.html
    /// https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice
    /// </summary>
    [pbr::OriginalName("NINE_SLICES")] NineSlices = 0,
    /// <summary>
    /// CENTER enables the texture to be rendered centered in relation to the
    /// element. If the element is smaller than the texture then the background
    /// should use the element as stencil to cut off the out-of-bounds area
    /// </summary>
    [pbr::OriginalName("CENTER")] Center = 1,
    /// <summary>
    /// STRETCH enables the texture to cover all the area of the container,
    /// adopting its aspect ratio.
    /// </summary>
    [pbr::OriginalName("STRETCH")] Stretch = 2,
  }

  #endregion

  #region Messages
  public sealed partial class PBUiBackground : pb::IMessage<PBUiBackground>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBUiBackground> _parser = new pb::MessageParser<PBUiBackground>(() => new PBUiBackground());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBUiBackground> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DCL.ECSComponents.UiBackgroundReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBUiBackground() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBUiBackground(PBUiBackground other) : this() {
      color_ = other.color_ != null ? other.color_.Clone() : null;
      texture_ = other.texture_ != null ? other.texture_.Clone() : null;
      textureMode_ = other.textureMode_;
      textureSlices_ = other.textureSlices_ != null ? other.textureSlices_.Clone() : null;
      uvs_ = other.uvs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBUiBackground Clone() {
      return new PBUiBackground(this);
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 1;
    private global::Memetaverse.Common.Color4 color_;
    /// <summary>
    /// default=(1.0, 1.0, 1.0, 1.0), pixel = color * sample2D(texture, uv)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Memetaverse.Common.Color4 Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "texture" field.</summary>
    public const int TextureFieldNumber = 2;
    private global::Memetaverse.Common.TextureUnion texture_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Memetaverse.Common.TextureUnion Texture {
      get { return texture_; }
      set {
        texture_ = value;
      }
    }

    /// <summary>Field number for the "texture_mode" field.</summary>
    public const int TextureModeFieldNumber = 3;
    private global::DCL.ECSComponents.BackgroundTextureMode textureMode_ = global::DCL.ECSComponents.BackgroundTextureMode.NineSlices;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DCL.ECSComponents.BackgroundTextureMode TextureMode {
      get { return textureMode_; }
      set {
        textureMode_ = value;
      }
    }

    /// <summary>Field number for the "texture_slices" field.</summary>
    public const int TextureSlicesFieldNumber = 4;
    private global::Memetaverse.Common.BorderRect textureSlices_;
    /// <summary>
    /// default=(1/3, 1/3, 1/3, 1/3)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Memetaverse.Common.BorderRect TextureSlices {
      get { return textureSlices_; }
      set {
        textureSlices_ = value;
      }
    }

    /// <summary>Field number for the "uvs" field.</summary>
    public const int UvsFieldNumber = 5;
    private static readonly pb::FieldCodec<float> _repeated_uvs_codec
        = pb::FieldCodec.ForFloat(42);
    private readonly pbc::RepeatedField<float> uvs_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// default=[0,0,0,1,1,0,1,0]: starting from bottom-left vertex clock-wise
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Uvs {
      get { return uvs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBUiBackground);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBUiBackground other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Color, other.Color)) return false;
      if (!object.Equals(Texture, other.Texture)) return false;
      if (TextureMode != other.TextureMode) return false;
      if (!object.Equals(TextureSlices, other.TextureSlices)) return false;
      if(!uvs_.Equals(other.uvs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (color_ != null) hash ^= Color.GetHashCode();
      if (texture_ != null) hash ^= Texture.GetHashCode();
      if (TextureMode != global::DCL.ECSComponents.BackgroundTextureMode.NineSlices) hash ^= TextureMode.GetHashCode();
      if (textureSlices_ != null) hash ^= TextureSlices.GetHashCode();
      hash ^= uvs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (color_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (texture_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Texture);
      }
      if (TextureMode != global::DCL.ECSComponents.BackgroundTextureMode.NineSlices) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TextureMode);
      }
      if (textureSlices_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TextureSlices);
      }
      uvs_.WriteTo(output, _repeated_uvs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (color_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (texture_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Texture);
      }
      if (TextureMode != global::DCL.ECSComponents.BackgroundTextureMode.NineSlices) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TextureMode);
      }
      if (textureSlices_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TextureSlices);
      }
      uvs_.WriteTo(ref output, _repeated_uvs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (texture_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Texture);
      }
      if (TextureMode != global::DCL.ECSComponents.BackgroundTextureMode.NineSlices) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TextureMode);
      }
      if (textureSlices_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TextureSlices);
      }
      size += uvs_.CalculateSize(_repeated_uvs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBUiBackground other) {
      if (other == null) {
        return;
      }
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::Memetaverse.Common.Color4();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.texture_ != null) {
        if (texture_ == null) {
          Texture = new global::Memetaverse.Common.TextureUnion();
        }
        Texture.MergeFrom(other.Texture);
      }
      if (other.TextureMode != global::DCL.ECSComponents.BackgroundTextureMode.NineSlices) {
        TextureMode = other.TextureMode;
      }
      if (other.textureSlices_ != null) {
        if (textureSlices_ == null) {
          TextureSlices = new global::Memetaverse.Common.BorderRect();
        }
        TextureSlices.MergeFrom(other.TextureSlices);
      }
      uvs_.Add(other.uvs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (color_ == null) {
              Color = new global::Memetaverse.Common.Color4();
            }
            input.ReadMessage(Color);
            break;
          }
          case 18: {
            if (texture_ == null) {
              Texture = new global::Memetaverse.Common.TextureUnion();
            }
            input.ReadMessage(Texture);
            break;
          }
          case 24: {
            TextureMode = (global::DCL.ECSComponents.BackgroundTextureMode) input.ReadEnum();
            break;
          }
          case 34: {
            if (textureSlices_ == null) {
              TextureSlices = new global::Memetaverse.Common.BorderRect();
            }
            input.ReadMessage(TextureSlices);
            break;
          }
          case 42:
          case 45: {
            uvs_.AddEntriesFrom(input, _repeated_uvs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (color_ == null) {
              Color = new global::Memetaverse.Common.Color4();
            }
            input.ReadMessage(Color);
            break;
          }
          case 18: {
            if (texture_ == null) {
              Texture = new global::Memetaverse.Common.TextureUnion();
            }
            input.ReadMessage(Texture);
            break;
          }
          case 24: {
            TextureMode = (global::DCL.ECSComponents.BackgroundTextureMode) input.ReadEnum();
            break;
          }
          case 34: {
            if (textureSlices_ == null) {
              TextureSlices = new global::Memetaverse.Common.BorderRect();
            }
            input.ReadMessage(TextureSlices);
            break;
          }
          case 42:
          case 45: {
            uvs_.AddEntriesFrom(ref input, _repeated_uvs_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
