
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: memetaverse.renderer.renderer_services
// file: memetaverse/renderer/renderer_services/transport.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;

namespace Memetaverse.Renderer.RendererServices {
public interface IClientTransportService
{
  IUniTaskAsyncEnumerable<Payload> OpenTransportStream(IUniTaskAsyncEnumerable<Payload> streamRequest);
}

public class ClientTransportService : IClientTransportService
{
  private readonly RpcClientModule module;

  public ClientTransportService(RpcClientModule module)
  {
      this.module = module;
  }

  
  public IUniTaskAsyncEnumerable<Payload> OpenTransportStream(IUniTaskAsyncEnumerable<Payload> streamRequest)
  {
      return module.CallBidirectionalStream<Payload>("OpenTransportStream", streamRequest);
  }

}
}
