
// AUTOGENERATED, DO NOT EDIT
// Type definitions for server implementations of ports.
// package: memetaverse.renderer.renderer_services
// file: memetaverse/renderer/renderer_services/emotes_renderer.proto
using Cysharp.Threading.Tasks;
using rpc_csharp;

namespace Memetaverse.Renderer.RendererServices {
public interface IClientEmotesRendererService
{
  UniTask<TriggerSelfUserExpressionResponse> TriggerSelfUserExpression(TriggerSelfUserExpressionRequest request);

  UniTask<SuccessResponse> TriggerSceneExpression(TriggerSceneExpressionRequest request);
}

public class ClientEmotesRendererService : IClientEmotesRendererService
{
  private readonly RpcClientModule module;

  public ClientEmotesRendererService(RpcClientModule module)
  {
      this.module = module;
  }

  
  public UniTask<TriggerSelfUserExpressionResponse> TriggerSelfUserExpression(TriggerSelfUserExpressionRequest request)
  {
      return module.CallUnaryProcedure<TriggerSelfUserExpressionResponse>("TriggerSelfUserExpression", request);
  }

  public UniTask<SuccessResponse> TriggerSceneExpression(TriggerSceneExpressionRequest request)
  {
      return module.CallUnaryProcedure<SuccessResponse>("TriggerSceneExpression", request);
  }

}
}
