name: Deployment Notification

on:
  pull_request:
    types: [ opened ]

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Memetaverse Unity-Renderer Deployment Notification
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@main
        with:
          message: |
            After the CI passes:

            ### Web
            This branch can be previewed at:
            - https://play.memetaverse.club/?explorer-branch=${{ github.head_ref }}
            - https://play.memetaverse.club/?explorer-branch=${{ github.head_ref }}

            ### Desktop:
            If you have the launcher installed ([download launcher](https://github.com/memetaverseproject/explorer-desktop-launcher/releases)) you can press open on the following link:
            - [Open custom protocol](https://renderer-artifacts.memetaverse.club/desktop/index.html?dcl://DESKTOP-BRANCH=${{ github.head_ref }})
            - [Open custom protocol with Developer Mode](https://renderer-artifacts.memetaverse.club/desktop/index.html?dcl://DESKTOP-BRANCH=${{ github.head_ref }}&DESKTOP-DEVELOPER-MODE)

            ### SDK 6/7:
            - [Open SDK7 scenes playground](https://playground.memetaverse.club/?explorer-branch=${{ github.head_ref }})
            - [Open SDK7 scenes in preview](https://sdk-test-scenes.memetaverse.club/?position=73,-8&realm=LocalPreview&explorer-branch=${{ github.head_ref }})
            - [Open SDK6 scenes in preview](https://sdk-test-scenes.memetaverse.club/?position=-1,27&realm=LocalPreview&explorer-branch=${{ github.head_ref }})

            ### More
            - Code coverage report: [https://renderer-artifacts.memetaverse.club/branch-coverage/${{ github.head_ref }}](https://renderer-artifacts.memetaverse.club/branch-coverage/${{ github.head_ref }})
            - Benchmark report: [https://renderer-artifacts.memetaverse.club/branch-benchmark/${{ github.head_ref }}/index.html](https://renderer-artifacts.memetaverse.club/branch-benchmark/${{ github.head_ref }}/index.html)

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
